### ISSUE TITLE
Mitglieder-Overlay fixen

### ISSUE THREAD

**Issue by LeoDJ** [opendata-heilbronn/codeforheilbronn-de#14]
Beim Hovern über die Contributors sieht das Overlay nicht so wirklich lesbar aus

(Icon zu groß, kein Hintergrund, etc)

![image](https://user-images.githubusercontent.com/5898657/36531248-944a545e-17bd-11e8-9e0b-fdcc3d96f166.png)

**Comment by grundid** [comment]
Ich habe das bisher nicht korrigiert, weil es mobil sowieso nicht funktioniert.
Vorschlag wäre, dass alle Vereinsmitglieder eine eigene Page bekommen und auf diese dann verlinkt wird.

**Comment by LeoDJ** [comment]
Finde ich okay, wenn der Name direkt auf der Seite auch angezeigt wird.

Hatten wir im alten Layout nicht auch eine Seite für die Mitglieder?

**Comment by grundid** [comment]
Ich habe bisher nur die Overlays gesehen. Die "contributors" sind im Moment als Data-Collection angelegt. Man müsste für jedes Mitglied eine .md Datei anlegen, die jeder etwas frei gestalten kann.

**Comment by LeoDJ** [comment]
Ich würde evtl. versuchen, alle Projekt-Meta-Informationen (Badge, Status, Links und Contributors) in eine Seitenleiste ähnlich der bereits im [Alembic Template](https://alembic.darn.es/elements/) vorhandenen zu packen.  
Diese muss sich im Mobillayout dann eben umordnen, also anstatt rechts an der Seite, bspw. über dem eigentlichen Content.

In dem Zuge würde ich mir auch das Contributors-Overlay nochmal anschauen und umstrukturieren.

**Comment by LeoDJ** [comment]
Fixed by #40
