### ISSUE TITLE
Webseite auf richtigen Webserver umziehen

### ISSUE THREAD

**Issue by LeoDJ** [opendata-heilbronn/codeforheilbronn-de#16]
Können @harmoniemand bzw. ich für den Verein sowieso kostenfrei auf unsere vServer schmeißen.

Gründe:
- HTTPS
- Bessere Rewrite Rules
- Freie Webserver Konfiguration

Natürlich soll continuous delivery weiterhin funktionieren.

TODO:
- [x] Travis Deployment
- [ ] Domain verbinden

**Comment by lukas-h** [comment]
Ich könnte das übernehmen @LeoDJ 
Ich würde das auf Firebase Hosting mit Travis als Deploy machen, was alles komplett kostenlos ist..

**Comment by harmoniemand** [comment]
Kann das https?

**Comment by lukas-h** [comment]
Ja, automatisch - muss man nix konfigurieren.

**Comment by lukas-h** [comment]
Da Github Pages ja jetzt HTTPS hat, wird das gar nicht mehr gebraucht
