### ISSUE TITLE
Wiki-Abschnitt

### ISSUE THREAD

**Issue by LeoDJ** [opendata-heilbronn/codeforheilbronn-de#26]
Die Webseite soll ein Wiki bekommen. In welcher Form ist nicht wirklich vorgegeben.

Allerdings wäre es vermutlich mit in Jekyll einfacher zu pflegen, als wenn man es extra aufsetzt. (Zwei Plattformen werden insgesamt weniger gepflegt als eine hybride)

Muss auch nicht wie ein klassisches Wiki aussehen, aber die einfache Verlinkung zwischen Seiten sollte idealerweise möglich sein.

**Comment by patrick246** [comment]
Joni hat im Slack HackMD vorgeschlagen, ein Markdown-basiertes Wiki mit vielen Features. https://github.com/hackmdio/hackmd
Zur Authentifizierung könnte man die Github-Authentifizierung so umschreiben, dass sie nur noch Github-User zulässt, die in der Open Data Heilbronn Orga sind

**Comment by LeoDJ** [comment]
Aktuell wird ein Wiki auf [Github angefangen](https://github.com/opendata-heilbronn/Wiki/wiki).
Man müsste das dann noch im Header verlinken.
