### ISSUE TITLE
Side Navigation flackert / wird kurzzeitig ausgeblendet FF59

### ISSUE THREAD

**Issue by raspyweather** [opendata-heilbronn/codeforheilbronn-de#32]
Repro:
1. http://codeforheilbronn.de/categories/#softwareclub
0. Scrollen, Mauszeiger nicht über Sidenavigation haben
0. [Effekt sollte auftreten]
Bild1:
Navigation komplett unsichtbar nach scrollen
![image](https://user-images.githubusercontent.com/23191735/38114428-9003cf2c-33a8-11e8-970d-d52819bb55d8.png)
Bild2:
Navigation teilweise nicht sichtbar (Einladung&Software Club durch flackern ausgeblendet)
![image](https://user-images.githubusercontent.com/23191735/38114489-d0e03b3e-33a8-11e8-9ccd-78320a973413.png)

**Comment by LeoDJ** [comment]
Could not reproduce.

**Comment by LeoDJ** [comment]
@raspyweather könntest du bitte nochmal prüfen, nachdem durch die große Änderung in #40 das Aside global verändert wurde?

**Comment by raspyweather** [comment]
in FF60 funktioniert es, in FF59 flackert es immernoch, vermutlich FF Bug
