### ISSUE TITLE
Email Feld nicht geprüft

### ISSUE THREAD

**Issue by raspyweather** [opendata-heilbronn/codeforheilbronn-de#6]
![image](https://user-images.githubusercontent.com/23191735/32938067-3bb25578-cb7b-11e7-9fa2-afe00466168f.png)
Es ist möglich bei leerem Feld die Request abzuschicken und bekommt sogar noch angezeigt, dass es erfolgreich war.

**Comment by patrick246** [comment]
https://github.com/opendata-heilbronn/codeforheilbronn-de/blob/f2bddb149416939fce0f7c7cb7ce582e56721eba/_includes/footer.html#L38

Die Funktion sollte grundlegende Email Validierung machen

**Comment by LeoDJ** [comment]
Bezog sich auf das alte Layout, nicht mehr relevant.
